config/routes.rb
RailsTodoJs::Application.routes.draw do
  get '/lists/:list_id/tasks/:id' => 'tasks#destroy'
  
  resources :lists do
    resources :tasks
  end
  

  get '/sandbox' => 'application#sandbox'

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  
  def add_task(task_hash)
    task_hash[:status] ||= 0
    tasks.build(task_hash)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  STATUSES = {
    0 => "incomplete",
    1 => "completed"
  }

  belongs_to :list

  def status_text
    STATUSES[status]
  end

  def completed?
    status == 1
  end

  def incomplete?
    status == 0
  end


  def complete!
    update(:status => 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def sandbox
    respond_to do |f|
      f.html
      f.js 
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.new
    @lists = List.all

    respond_to do |f|
      f.xml {render :xml => @lists}
      f.json {render :json => @lists}
      f.html
    end
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      @lists = List.all
      render :index
    end
  end

  def show
    @list = List.find(params[:id])
    @task = Task.new
  end

  private
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def create
    @list = List.find(params[:list_id])
    @task = @list.add_task(task_params)
    @task.save

    respond_to do |f|
      f.html {redirect_to @list}
      f.js
    end

  end
  
  def update
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])

    @task.update(task_params)
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id]).destroy

    respond_to do |f|
      f.js
    end
  end

  private
    def task_params
      params.require(:task).permit(:description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_js(*args)
    j(render(*args))
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def li_for_task(task)
    content_tag :li, :data => {:id => task.id, :class => task.class.to_s.downcase}, :class => task.status_text do
      yield
    end
  end

end

app/views/application/sandbox.html.erb
<h1>Avi's Sandbox</h1>

<script>
  // Send an Ajax Request to Get More Javascript
  // and then EXECUTE THAT JAVASCRIPT AS THOUGHT IT WAS
  // HERE THE ENTIRE TIME.
  // $.getScript("/sandbox");

</script>
<h2>Wait for it</h2>

app/views/application/sandbox.js.erb
alertSandbox();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTodoJs</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="todoapp">
    <%= yield %>
  </section>

  <footer id="info">
    <p>Double-click to edit a todo | <%= link_to_unless_current "Home", root_path %></p>
    <p>Written by <a href="https://flatironschool.com">Flatiron School</a></p>
    <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
  </footer> 
</body>
</html>

app/views/lists/index.html.erb
<header id="header">
  <h1>Your Lists</h1>
  <%= form_for(@list) do |f| %>
    <%= f.text_field :name, :id => "new-todo", 
                     :placeholder => "Make a new list", 
                     :autofocus => true %>

  <% end %>
</header>
<section id="main">
  <ul id="todo-list">
    <% @lists.each do |list| %>
    <li>
      <div class="view">
        <label><%= link_to list.name, list %></label>
        <button class="destroy"></button>
      </div>          
    </li>
    <% end %>        
  </ul>
</section>

app/views/lists/show.html.erb
<header id="header">
  <h1><%= @list.name %></h1>
  <%#= form_for(@list.tasks.build, :url => list_tasks_path(@list)) do |f| %>
  <%= form_for([@list, @task], :remote => true) do |f| %>
    <%= f.text_field :description, 
                     :id => "new-todo", 
                     :placeholder => "What needs to be done?", 
                     :autofocus => true %>
  <% end %>
</header>

<section id="main">
  <input id="toggle-all" type="checkbox" onclick="">

  <label for="toggle-all">Mark all as complete</label>
  <%= content_tag :ul, :data => {:id => @list.id}, :id => "todo-list" do %>
    <%= render @list.tasks.order("created_at DESC") %> 
  <% end %>
</section>

<footer id="footer">
  <span id="todo-count"><strong>1</strong> item left</span>
  <ul id="filters">
    <li>
      <a data-filter="all" href="#">All</a>
    </li>
    <li>
      <a data-filter='active' href="#">Active</a>
    </li>
    <li>
      <a data-filter='completed' href="#">Completed</a>
    </li>
  </ul>
  <button id="clear-completed">Clear completed (1)</button>
</footer>

app/views/tasks/_task.html.erb
<%= li_for_task(task) do %>
  <div class="view">
    <input class="toggle" type="checkbox" <%= "checked" if task.completed? %> />
    <label><%= task.description %></label>
    <%= button_to "✖", list_task_path(task.list, task), :class => "destroy task", :remote => true, :method => :delete %>

  </div>          

  <input value="<%= task.description %>" class="edit">
<% end %>

app/views/tasks/create.js.erb
$("ul#todo-list").prepend("<%= render_js @task %>");
$("form#new_task input").val("")

app/views/tasks/destroy.js.erb
$("li[data-id=<%= @task.id %>]").fadeOut(function(){
  $(this).remove()
});

app/views/tasks/update.js.erb
$("li[data-id=<%= @task.id %>]").replaceWith("<%= render_js @task %>");